### ISSUE TITLE
[Bug]: Not Modifying World Description or Cover Image on Import

### ISSUE THREAD

**Issue by Nargath** [foundryvtt/foundryvtt-premium-content#243] opened 2023-02-10 03:22 UTC
### What happened?

When activating, then importing the Abomination Vaults module for the first time into a world, even if the "Customize World Details" is ticked during the import selection process, the World Description and the Cover Image aren't modified.

I actioned this about a month ago for a new game I was running, and also re-tested it today on a fresh test world on PF2e version 4.7.4.

Not a major bug, and can easily add these in manually, just seems odd that the tickbox doesn't function.

### What package are you reporting this for?

Pathfinder: Abomination Vaults by Paizo

### Version

2.0.0

**Comment by silvative** [comment] 2023-02-13 10:08
Closing as a duplicate of https://github.com/foundryvtt/foundryvtt-premium-content/issues/216

**Closed by silvative** 2023-02-13 10:08 UTC
Labels: bug, pf2e-abomination-vaults
