### ISSUE TITLE
[Bug]: Unicode character to mark currently open journal page fails to render for macOS

### ISSUE THREAD

**Issue by anathemamask** [foundryvtt/foundryvtt-premium-content#524] opened 2024-03-21 21:59 UTC
### What happened?

originally reported by tslays

The abomination vaults journal entry pages (and likely the beginner box ones as well) use the unicode character ⮚ to indicate which journal entry page is currently being viewed.

This unicode character apparently doesn't exist in the default fonts for macOS 14.4 so users instead get large square block.

Suggest switching to a character that does render , this may require communicating with a macOS user to confirm that the character shows, but some options i've already confirmed are: 

⇛
⇨
or
⇒

### What package are you reporting this for?

Pathfinder: Abomination Vaults

### Version

3.1.0

**Comment by silvative** [comment] 2024-03-24 15:02
Resolved in BB update 4.0.0 by replacing the unicode character with an image asset instead- still to be done for AV and Ferncombe

**Comment by silvative** [comment] 2024-03-25 15:02
Change also applied for AV dev branch (not yet released)

**Closed by silvative** 2024-03-25 15:02 UTC
Labels: bug, pf2e-abomination-vaults, css

**Comment by tslays** [comment] 2024-03-26 06:31
Thanks for fixing it. I just checked it and it workes as intended. Much appreciated and one of the reasons that I will keep supporting your great work!
