### ISSUE TITLE
[Bug]: Incomplete Sentence in 

### ISSUE THREAD

**Issue by Puggers** [foundryvtt/foundryvtt-premium-content#136] opened 2022-11-01 17:43 UTC
### What happened?

In R01. Entryway:

...Across a wide courtyard and up a short landing the facade looms in testament to what once was. Two great oaken doors engraved with the bar entrance to the manor proper. 

This feels like something was omitted during editing and never put back. 

### What package are you reporting this for?

A House Divided

### Version

1.0.2

**Comment by anathemamask** [comment] 2022-11-10 01:05
Duplicate of #151

**Closed** 2022-11-10 01:05 UTC
Labels: bug, a-house-divided
