### ISSUE TITLE
[Bug]: Harrow - cards chosen in the Choosing always show in the Spread

### ISSUE THREAD

**Issue by narchymaps** [foundryvtt/foundryvtt-premium-content#288] opened 2023-05-05 08:29 UTC
### What happened?

The chosen cards are "reshuffled" in to the Spread deck, but should have a random chance to be drawn. Tried multiple times. Example below is nine players, with all nine cards appearing again. 

> Remove the nine cards of the suit you have chosen from the harrow deck and shuffle those nine. Spread the cards you chose facedown in front of you. Instruct your subjects to each pick one card. The chosen card has a message for that person about their current 5 place in the world and in relation to the question at hand. Using the descriptions on pages 9–14, interpret each card to define that subject’s role for the upcoming series of events.
> 
> **If this card** appears in the spread that follows, it applies most strongly to the person who chose that role and should be interpreted accordingly.
> 

![image](https://user-images.githubusercontent.com/118607328/236410888-d0e66042-e1ab-43cb-a686-042ce78a41ee.png)

![image](https://user-images.githubusercontent.com/118607328/236411018-46fb1b6b-9b0c-4b0f-9918-207a4392f215.png)

### What package are you reporting this for?

Pathfinder: Harrow Deck

### Version

1.0.1

**Comment by silvative** [comment] 2023-05-16 17:15
This is the expected outcome with the release version of the deck, but will be amended in an upcoming update. For now I am closing this issue as a duplicate of https://github.com/foundryvtt/pf2e-decks-harrow/issues/31

**Closed by silvative** 2023-05-16 17:15 UTC
Labels: bug, pf2e-decks-harrow
