### ISSUE TITLE
[Bug]: [AV] Warnings on fresh import

### ISSUE THREAD

**Issue by esheyw** [foundryvtt/foundryvtt-premium-content#128] opened 2022-10-18 01:27 UTC
### What happened?

This doesn't seem to affect anything, at least, the creature data seems to all be correct as far as I've poked around, but importing the adventure in a fresh world, v10.288, system 4.2.6, module 1.2.0 produces a bunch of ![image](https://i.imgur.com/buINylB.png) etc, followed by a couple deprecation warnings for the import process (these idc about, assuming expected). Pasted one of the almost-identicals along with the deprecation warnings just for completeness.

### What package are you reporting this for?

Pathfinder: Abomination Vaults by Paizo

### Version

1.2.0

### Relevant log output

```shell
[pf2e-abomination-vaults] Compendium source data for "Otari Guard" [rsATu823vatRe7QJ] not found in pack pf2e.abomination-vaults-bestiary
#mergeCompendiumActors @ importer.mjs:136
await in #mergeCompendiumActors (async)
_prepareImportData @ importer.mjs:63
await in _prepareImportData (async)
_updateObject @ foundry.js:61765
_onSubmit @ foundry.js:5874
commons.js:1703

Error: You are accessing BasePackage#data which is now deprecated in favor of referencing schema fields directly on the BasePackage instance.
Deprecated since Version 10
Backwards-compatible support will be removed in Version 12
    at logCompatibilityWarning (commons.js:1692:19)
    at get data [as data] (commons.js:11734:7)
    at Object.handler (adventure.mjs:72:28)
    at PF2EAdventureImporter._importContent (importer.mjs:83:20)
    at async PF2EAdventureImporter._updateObject (foundry.js:61784:32)
    at async PF2EAdventureImporter._onSubmit (foundry.js:5874:7)
logCompatibilityWarning @ commons.js:1703
get data @ commons.js:11734
handler @ adventure.mjs:72
_importContent @ importer.mjs:83
commons.js:1703

Error: You are accessing BasePackage#name which is now deprecated in favor of id.
Deprecated since Version 10
Backwards-compatible support will be removed in Version 13
    at logCompatibilityWarning (commons.js:1692:19)
    at get name [as name] (commons.js:11719:7)
    at Object.handler (adventure.mjs:72:33)
    at PF2EAdventureImporter._importContent (importer.mjs:83:20)
    at async PF2EAdventureImporter._updateObject (foundry.js:61784:32)
    at async PF2EAdventureImporter._onSubmit (foundry.js:5874:7)
logCompatibilityWarning @ commons.js:1703
get name @ commons.js:11719
handler @ adventure.mjs:72
_importContent @ importer.mjs:83
commons.js:1703
Error: You are accessing BasePackage#data which is now deprecated in favor of referencing schema fields directly on the BasePackage instance.
Deprecated since Version 10
Backwards-compatible support will be removed in Version 12
    at logCompatibilityWarning (commons.js:1692:19)
    at get data [as data] (commons.js:11734:7)
    at Object.handler (adventure.mjs:73:31)
    at PF2EAdventureImporter._importContent (importer.mjs:83:20)
    at async PF2EAdventureImporter._updateObject (foundry.js:61784:32)
    at async PF2EAdventureImporter._onSubmit (foundry.js:5874:7)
logCompatibilityWarning @ commons.js:1703
get data @ commons.js:11734
handler @ adventure.mjs:73
_importContent @ importer.mjs:83
commons.js:1703 

Error: You are accessing BasePackage#data which is now deprecated in favor of referencing schema fields directly on the BasePackage instance.
Deprecated since Version 10
Backwards-compatible support will be removed in Version 12
    at logCompatibilityWarning (commons.js:1692:19)
    at get data [as data] (commons.js:11734:7)
    at Object.handler (adventure.mjs:81:20)
    at async PF2EAdventureImporter._importContent (importer.mjs:83:7)
    at async PF2EAdventureImporter._updateObject (foundry.js:61784:32)
    at async PF2EAdventureImporter._onSubmit (foundry.js:5874:7)
logCompatibilityWarning @ commons.js:1703
get data @ commons.js:11734
handler @ adventure.mjs:81
await in handler (async)
_importContent @ importer.mjs:83
commons.js:5771 

You are calling DataModel#update which is renamed to DataModel#updateSource
update @ commons.js:5771
handler @ adventure.mjs:81
await in handler (async)
_importContent @ importer.mjs:83
```

**Comment by silvative** [comment] 2022-11-04 18:50
I can confirm that I see these warnings too. It seems as though the import script is checking the AV bestiary for every actor, even those that come from a different compendium. It doesn't seem to result in any negative outcomes though.

**Comment by silvative** [comment] 2022-11-04 19:39
Closing as a duplicate of https://github.com/foundryvtt/foundryvtt-premium-content/issues/113

**Closed** 2022-11-04 19:49 UTC
Labels: bug, pf2e-abomination-vaults
