### ISSUE TITLE
[Bug]: Hex editor pops up when doubleclicking if the border tool is active

### ISSUE THREAD

**Issue by alexbrault** [foundryvtt/foundryvtt-premium-content#436] opened 2023-12-14 23:14 UTC
### What happened?

In the Stolen Lands map, the Hex editor opens when double-clicking the map if the border tool is active, even if the Hexploration tool is inactive

### What package are you reporting this for?

Pathfinder: Kingmaker

### Version

2.0.0

**Comment by tagnullde** [comment] 2023-12-15 06:16
It also pops up when trying to open journals or actor sheets. Would be cool if the Hex Map would "notice" what I try to click (Journal, Actor) and won't open the hex editor regardless of the tool state unless I specifically click on the hex/map.

**Comment by silvative** [comment] 2024-02-18 17:55
Closing as a duplicate of #427

**Closed by silvative** 2024-02-18 17:55 UTC
Labels: bug, pf2e-kingmaker
