### ISSUE TITLE
[Bug]: Imported multiple times, even to an empty world, Harrow module not giving me any content

### ISSUE THREAD

**Issue by Prince-Xander** [foundryvtt/foundryvtt-premium-content#494] opened 2024-02-10 01:27 UTC
### What happened?

The Pathfinder Harrow official module is not adding any content whatsoever, am I doing something wrong when I import it?

### What package are you reporting this for?

Pathfinder: Harrow Deck

### Version

1.1.1

**Comment by silvative** [comment] 2024-02-25 19:24
Hi, I'm sorry to hear about the issue- I've just tested installing the module on the latest core + system + module versions and it does seem to be working for me. As far as I know, this should be working- could I ask you to check the versions again? If everything is up to date and it still doesn't work, it may be worth trying to reinstall the module or disabling all other modules, just to make sure we control for all possible variables.

**Comment by silvative** [comment] 2024-05-18 13:56
Hi, as I'm updating the module for V12 I am still unable to reproduce this issue, so I'm going to close it as nonrepro- if you are having issues with importing content, please do reach out to us via email so that we can do some support/troubleshooting and get to the bottom of the issue. I'm hoping that the lack of updates here means that the problem was resolved, though!

**Closed by silvative** 2024-05-18 13:56 UTC
Labels: bug, nonrepro, pf2e-decks-harrow
