### ISSUE TITLE
[Bug]: Adventure Module won't import

### ISSUE THREAD

**Issue by Kalsiar** [foundryvtt/foundryvtt-premium-content#549] opened 2024-05-02 20:55 UTC
### What happened?

When I tried to import the adventure using the module it gave me an error saying:

Cannot read properties of undefined(reading '0')

![error message](https://github.com/foundryvtt/foundryvtt-premium-content/assets/168781410/bf06bccb-8a3e-4a33-8bee-839a9ca41c99)

### What package are you reporting this for?

Pathfinder: Kingmaker

### Version

2.1.0

**Comment by silvative** [comment] 2024-05-13 18:25
Hi, it looks like in your screenshot there is no scene active on the canvas- I think Foundry expects a scene to be active for a lot of things, so I was wondering if that might be related to your issue. If you create and activate a scene (even a blank one), does the importer work? If that fixes it, we'll still want to try and make the import process more resilient, but it may at least resolve your problems in the immediate term.

**Comment by silvative** [comment] 2024-05-18 15:30
Testing in V12 I cannot reproduce this issue, even with no scenes in the world, so I'm going to close it as nonrepro for now- but please get back to me if you are still encountering this, or feel free to send us an email so that we can have a support/troubleshooting session and get to the bottom of it.

**Closed by silvative** 2024-05-18 15:30 UTC
Labels: bug, pf2e-kingmaker
