### ISSUE TITLE
Error message relating to scene image size

### ISSUE THREAD

**Issue by GuiFzord** [foundryvtt/foundryvtt-premium-content#467] opened 2024-01-24 00:59 UTC
### What happened?

so i was playing Kingmaker today (the official module)  but this error displayed in the images kept happening in most maps:
![imagem_2024-01-23_215045092](https://github.com/foundryvtt/foundryvtt-premium-content/assets/114864568/d45f9be7-064a-44e5-b1c3-e8078e596c7c)
![imagem_2024-01-23_215103131](https://github.com/foundryvtt/foundryvtt-premium-content/assets/114864568/a4b272d6-435f-4bc2-b6d2-cafdb81c362f)
Clarifying that I am a player, not the GM, I do not own the module that the GM has.

### What package are you reporting this for?

Pathfinder: Kingmaker

### Version

2.0.0

### Relevant log output

```shell
I don't exactly know what this is (probably due to language barrier) but suppose it's this information form the console:
Foundry VTT | Loading 73 Assets foundry.js:29359
[Assets] Asset id modules/pf2e-kingmaker/assets/maps/aldori-siege-west/background.webp was not found in the Cache @ earcut.js:128
The dimensions of your configured Foreground Layer image do not match the dimensions of the Background Layer image for this scene. The foreground has been resized which may have undesired results. foundry.js:68326
```

**Comment by anathemamask** [comment] 2024-01-30 03:41
High likelihood this issue is caused by having less than 4GB available on your computer's primary drive; this is a common chrome bug with cache

**Comment by silvative** [comment] 2024-02-19 14:40
Closing as nonrepro under the assumption that the root cause is the Chrome bug mentioned above

**Closed by silvative** 2024-02-19 14:40 UTC
Labels: bug, pf2e-kingmaker
