### ISSUE TITLE
[Bug]: Abomination Vaults doesn't import actors and items on v10

### ISSUE THREAD

**Issue by droideck** [foundryvtt/foundryvtt-premium-content#125] opened 2022-10-08 20:03 UTC
### What happened?

I've made a fully clean Foundry VTT v10.287 install and I've tried to import Paizo's Abomination Vaults but even though it says it's successful, it doesn't import Actors and Items at all.

Steps to reproduce:

1. Make a clean  Foundry VTT v10.287 (tested on both Windows 11 and Linux Fedora 35);
2. Remove `.local/share/FoundryVTT`;
3. Run `foundryvtt` executable;
4. Install Pathfinder 2e system and Abomination Vaulst Module;
5. Create a world;
6. Enable the Abomination Vaults module;
7. Make sure that'll checkboxes are checked (all content);
8. Import the content;
9. Check Actors and Items tabs and try to click on an actor on any Abomination Vaults map.

Expected results:
There are imported Actors and Items;
An actor is opened on Abomination Vaults map.

Actual results:
There are no imported Actors and Items;
An actor is not opened on Abomination Vaults map (not found).

### What package are you reporting this for?

Pathfinder: Abomination Vaults by Paizo

### Version

10.287 

### Relevant log output

```shell
The only error I see in logs:


Uncaught (in promise) Error: You must provide a Scene Document to draw the Canvas.
    at Canvas.draw (foundry.js:23515:13)
    at ScenePF2e._onUpdate (foundry.js:20971:87)
    at ClientDatabaseBackend.callback (foundry.js:12766:11)
    at foundry.js:12715:43
    at Array.map (<anonymous>)
    at ClientDatabaseBackend._handleUpdateDocuments (foundry.js:12715:33)
    at ClientDatabaseBackend._updateDocuments (foundry.js:12592:17)
    at async ScenePF2e.updateDocuments (commons.js:6128:23)
    at async PF2EAdventureImporter._importContent (foundry.js:61852:17)
    at async PF2EAdventureImporter._importContent (importer.mjs:80:26)
```
```

**Comment by aaclayton** [comment] 2022-10-09 23:00
Duplicate of #124

**Closed by aaclayton** 2022-10-09 23:00 UTC
Labels: bug
