### ISSUE TITLE
[Bug]: PF2e Beginner Box - Floor 1, Room 11 & Floor 2 Room 17 Kobold warriors are super small

### ISSUE THREAD

**Issue by Peach774** [foundryvtt/foundryvtt-premium-content#529] opened 2024-03-27 17:08 UTC
### What happened?

The kobold warriors in room 11 and room 17 are extremely small (had to be manually scaled to 1.2 to be the correct size), but the compendium places them at the right size.

### What package are you reporting this for?

Pathfinder: Beginner Box

### Version

4.0.0

**Comment by silvative** [comment] 2024-04-16 13:49
Hi, can you confirm this is the case with a fresh import?

The latest version of the module did replace the token for these guys with one that requires a different scale, so if the adventure isn't reimported, they'll appear to be too small.

If they're not being imported correctly even in fresh worlds, then we'll need to take another stab at packaging the adventure with the correct scale- I'm wondering if I perhaps didn't set them for the actors, only the tokens, so they're being overwritten!

**Comment by MothMariner** [comment] 2024-04-17 00:45
Confirming these on a fresh install. 

Kobold warriors in rooms 11 and 17 are very small. The kobold warriors in room 7 are the correct size.

The kobold warriors in room 11 might be the cause of the issue - they're in the positions that the spike traps should be, and the spike traps are missing - maybe they got resized thinking they were spike traps? Either way room 11 need correcting to match the layout shown in the adventure image... maybe I should start a different issue for that.

**Comment by Peach774** [comment] 2024-04-17 00:57
> Hi, can you confirm this is the case with a fresh import?
> 
> The latest version of the module did replace the token for these guys with one that requires a different scale, so if the adventure isn't reimported, they'll appear to be too small.
> 
> If they're not being imported correctly even in fresh worlds, then we'll need to take another stab at packaging the adventure with the correct scale- I'm wondering if I perhaps didn't set them for the actors, only the tokens, so they're being overwritten!

Also confirming these on a fresh install.

**Comment by silvative** [comment] 2024-05-14 13:02
Thanks for the additional reports guys- I was able to replicate this after doing some more testing, I think I got thrown off because it was only affecting some of the kobolds! It should be fixed in the next version.

**Closed by silvative** 2024-05-14 13:02 UTC
Labels: bug, pf2e-beginner-box
