### ISSUE TITLE
[Bug]: Pact of the Blade not using CHA as its attack and damage mod

### ISSUE THREAD

**Issue by zzahringer** [foundryvtt/foundryvtt-premium-content#731] opened 2024-09-19 16:03 UTC
### What happened?

Pact of the Blade is not overriding the weapon's attack and damage mod with Charisma like it should. As far as I can tell, it's missing those items in the applied active effect.

To reproduce:
- Create a level 3 Warlock
- Give it Pact of the Blade
- Give the Warlock a 15 Charisma
- Give the Warlock a Dagger
- Edit Pact of the Blade's Effect: Enchantment and change `system.properties.foc` to `system.properties` (due to another bug with this particular class feature)
- Click on Pact of the Blade class feature to so it's ability displays in the chat area
- Drag and drop the Dagger into the chat card to apply the pact weapon effect to it
- Make an attack with the enchanted weapon
- note that the attack roll does not consider the Charisma as the ability modifier, and that it's only applying the Prof mod.

As an example of how to fix this Enchantment, consider checking out True Strike. (as suggested by maxobremer)

### What package are you reporting this for?

Dungeons & Dragons Player's Handbook

### Version

1.0.0

**Comment by trioderegion** [comment] 2024-09-19 16:33
Duplicate of #679

**Closed by trioderegion** 2024-09-19 16:33 UTC
Labels: bug, duplicate, dnd-players-handbook

**Comment by zzahringer** [comment] 2024-09-19 16:51
I was aware of 679, but that issue only calls out the .foc breaking the weapon (not being clickable), but does not address the missing modifications in the Enchantment so that it uses CHA for the attack and damage. Is there a way to make sure this above issue doesn't get lost in the update to Pact of the Blade?

**Comment by lholden** [comment] 2024-09-20 22:20
> Duplicate of #679

@trioderegion I just wanted to repeat what @zzahringer said. The `system.properties.foc` fix addresses the non responsive issue, but not the CHA issue.

@zzahringer I manually adjusted the ability modifier used in the Attack Activity. I couldn't figure out the right thing to change in the enchantment to modify it.
